### PR TITLE
Added insight into the number of remaining requests

### PR DESCRIPTION
**Pull request by ysimonson**
Added this to get an idea if some optimizations will need to be made before rolling this out to more repos

### CODE REVIEW

**Comment by ian-axelrod** [comment]
You should make tickets for these prs so that we can track work done on tars.

**Comment by ysimonson** [comment]
How about I make a ticket for tars in general, that covers the scope of work for this week, and then a ticket for each effort after this week? That way the many tweaks I make in the coming days as issues surface up - e.g. this one - don't require the creation of lots of tickets.

**Comment by ian-axelrod** [comment]
Yeah that's fine too.

**Comment by ysimonson** [comment]
https://www.pivotaltracker.com/story/show/139393063

**Pull request merged**
